-- AlterTable
ALTER TABLE "contacts" ALTER COLUMN "phone_2" DROP NOT NULL,
ALTER COLUMN "phone_3" DROP NOT NULL,
ALTER COLUMN "phone_4" DROP NOT NULL,
ALTER COLUMN "phone_5" DROP NOT NULL,
ALTER COLUMN "contact_1" DROP NOT NULL,
ALTER COLUMN "contact_2" DROP NOT NULL,
ALTER COLUMN "contact_3" DROP NOT NULL,
ALTER COLUMN "contact_4" DROP NOT NULL,
ALTER COLUMN "contact_5" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "observations" DROP NOT NULL;
