# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    env:
      working-directory: ./backend

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./backend/yarn.lock
        
    - name: Install dependencies
      run: yarn
      working-directory: ${{env.working-directory}}
    
    - name: Build application
      run: yarn build
      working-directory: ${{env.working-directory}}
    
    - name: Stop pm2
      run: pm2 delete agenda-server -f
      if: ${{failure()}}
      working-directory: ${{env.working-directory}}
      
    - name: Start pm2
      run: pm2 start dist/server.js --name agenda-server -f
      working-directory: ${{env.working-directory}}
      
    - name: Save pm2
      run: pm2 save -f
    
